In [85]:
import numpy as np

In [86]:
a=[1,2,3,4,'apple']
b=np.array(a)

print(b)   # deals with same datatype only

['1' '2' '3' '4' 'apple']


In [87]:
#dimesnions - 0 

c=np.array(34)

c.ndim


0

In [88]:
# dimesnion - 1
b.ndim

1

In [89]:

ar1= np.arange(0,100000000)
print(ar1)

[       0        1        2 ... 99999997 99999998 99999999]


In [90]:
ar1=[]
for x in range(1,100000000):
    ar1.append(x)

In [91]:
ar2=np.logspace(1,3,3)
print(ar2)

[  10.  100. 1000.]


In [92]:
ar2=np.linspace(1,3,3,dtype=int)
print(ar2)

[1 2 3]


In [93]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [94]:
print(np.ones([2,3],dtype=int))

[[1 1 1]
 [1 1 1]]


In [95]:
print(np.full(10,2))
print(np.full([2,4],7))

[2 2 2 2 2 2 2 2 2 2]
[[7 7 7 7]
 [7 7 7 7]]


In [96]:
print(np.empty([2,3]))

[[3.47739925e-081 4.08148455e-033 2.90129665e-057]
 [1.09325584e-042 9.68248667e-071 7.56571287e-307]]


In [97]:
print(np.random.rand(10))

[0.32360137 0.74968057 0.39365591 0.38531804 0.49745175 0.40453149
 0.9562575  0.60273234 0.04412228 0.79827611]


In [98]:
print(np.random.randint(1,100))

86


In [99]:
print(np.random.randint(1,100,size=(2,3)))

[[57 80 70]
 [87 68 60]]


In [100]:
print(np.random.randint(1000,10000,size=(2,10)))

[[9752 2889 9029 6044 2442 9918 6979 9391 5146 8599]
 [6408 9009 8439 8055 5040 7748 3140 8596 1667 8669]]


In [101]:
print(np.array([1,2,3,4,5.1]))

[1.  2.  3.  4.  5.1]


In [102]:
new1=np.array([1,2,3,4,4],dtype=int)
print(new1)

new2= new1.astype(np.float64)
print(new2)


[1 2 3 4 4]
[1. 2. 3. 4. 4.]


In [103]:
new3= np.array([[1,2,3,4],[5,6,7,8]])
print(new3)
new3.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [104]:
new3.shape
new3.size

8

In [105]:
new4=np.array([[1,2,3,4],[5,6,7,8]])
print(new4.ndim)

2


In [106]:
print(new4.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [112]:

new4[0]=100
new5=new4.ravel()
new5[0]=999
print(new4)


[[999 100 100 100]
 [  5   6   7   8]]


In [ ]:
new4[0]=100
new6=new4.flatten()
new6[0]=777

print(new4)


[[100 100 100 100]
 [  5   6   7   8]]


In [ ]:
ad1=np.array([1,2,3,4,5])

ad2=np.array([1,2,3,4,5])

print(ad1+ad2)
sq1=ad1*ad2
 
print(np.sqrt(sq1))

[ 2  4  6  8 10]
[1. 2. 3. 4. 5.]


In [123]:
mat1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [126]:
print(mat1[0:2,0:4])

[[1 2 3 4]
 [5 6 7 8]]


In [128]:
print(mat1[1: ,2:])

[[ 7  8]
 [11 12]]


In [130]:
for x in np.nditer(mat1):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [131]:
at= np.array([[1,2,3],[4,5,6],[7,8,9]])


In [132]:
at.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [133]:
at2= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [136]:
a = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])

print(a.shape)

(2, 2, 2)


In [142]:
a = np.arange(24).reshape(2,2,-1)
print(a)
print(a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
(2, 2, 6)


In [5]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [3]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
a2=np.array([[11,12,13,14],[15,16,17,8]])
a3=np.array([[21,22,23,24],[25,26,27,28]])

In [10]:
print(np.vstack((a1,a2,a3)))
print(np.hstack((a1,a2,a3)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17  8]
 [21 22 23 24]
 [25 26 27 28]]
[[ 1  2  3  4 11 12 13 14 21 22 23 24]
 [ 5  6  7  8 15 16 17  8 25 26 27 28]]


In [4]:
import numpy as np
print(np.where(a1>2,"high","low"))

[['low' 'low' 'high' 'high']
 ['high' 'high' 'high' 'high']]
